// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course_View.Models;

public partial class Course
{
    public int id { get; set; }

    public string name { get; set; }

    public int? credit_hours { get; set; }

    public int instructor_id { get; set; }

    public int? preRequest { get; set; }

    public virtual Instructor instructor { get; set; }

    public virtual Course preRequestNavigation { get; set; }
}