// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course_View.Models;

public partial class Instructor
{
    public int id { get; set; }

    public string name { get; set; }

    public int? age { get; set; }

    public string mobile { get; set; }

    public string major { get; set; }

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}